# ==============================================================================
# MousseRTP - Java Minecraft Plugin
# Copyright (c) 2026 Daperkz
#
# config
# ==============================================================================

# --------------------------------------------------
# CONFIGURATION GÉNÉRALE
# --------------------------------------------------
language: "fr"
cooldown-seconds: 30
countdown-seconds: 3
move-cancel-distance: 1.0
max-location-attempts: 80

# --------------------------------------------------
# CONFIGURATION DES DIMENSIONS
# --------------------------------------------------
dimensions:
  overworld:
    enabled: true
    world-name: "MousseSMP"
    min-x: -10000
    max-x: 10000
    min-z: -10000
    max-z: 10000
  nether:
    enabled: true
    world-name: "MousseSMP_nether"
    min-x: -2500
    max-x: 2500
    min-z: -2500
    max-z: 2500
  end:
    enabled: true
    world-name: "MousseSMP_the_end"
    min-x: -5000
    max-x: 5000
    min-z: -5000
    max-z: 5000

# --------------------------------------------------
# CONFIGURATION DES EFFETS SONORS (SOUNDS)
# --------------------------------------------------
sounds:
  start:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    volume: 1.0
    pitch: 0.8
  countdown:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_HARP"
    volume: 1.0
    # Pitch increases automatically as countdown gets closer to 0
    pitch-increase: true
    base-pitch: 1.0
  cancel-moved:
    enabled: true
    sound: "ENTITY_ITEM_BREAK"
    volume: 1.0
    pitch: 0.5
  teleport-success:
    enabled: true
    sound: "ENTITY_ENDERMAN_TELEPORT"
    volume: 1.0
    pitch: 1.0

# --------------------------------------------------
# CONFIGURATION DE L'INTERFACE
# --------------------------------------------------
gui:
  title: "<blue><b>RANDOM TELEPORT</b></blue>"
  rows: 3
  fill-empty: false
  fill-item: GRAY_STAINED_GLASS_PANE
  items:
    overworld:
      slot: 11
      material: GRASS_BLOCK
      name: "<green><b>Overworld</b></green>"
      lore:
        - "<gray>Cliquer pour se téléporter dans l'Overworld."
      dimension: "overworld"
    nether:
      slot: 13
      material: NETHER_BRICKS
      name: "<red><b>Nether</b></red>"
      lore:
        - "<gray>Cliquer pour se téléporter dans le Nether."
      dimension: "nether"
    end:
      slot: 15
      material: END_STONE
      name: "<yellow><b>The End</b></yellow>"
      lore:
        - "<gray>Cliquer pour se téléporter dans l'End."
      dimension: "end"
