# ==============================================================================
# DaperkzRTP - Java Minecraft Plugin
# Copyright (c) 2026 Daperkz
#
# plugin
# ==============================================================================

name: DaperkzRTP
version: '${project.version}'
main: com.daperkz.rtp.RTPPlugin
api-version: '1.20'
folia-supported: true
author: Daperkz
description: High performance asynchronous RTP plugin.

permissions:
  Daperkz.rtp:
    description: Permission to use /rtp
    default: true
  Daperkz.rtp.admin:
    description: Permission to reload the plugin
    default: op

commands:
  rtp:
    description: Teleport the player at a random secure place
    permission: Daperkz.rtp
    permission-message: "<red>You do not have permission to use this command."
